const {
  PORT,
  PAGE_NUMBER,
  PAGE_SIZE,

  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_NAME,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
} = process.env;

module.exports = {
  PORT: PORT || 80,
  PAGE_NUMBER_DEFAULT: parseInt(PAGE_NUMBER || 1, 10),
  PAGE_SIZE_DEFAULT: parseInt(PAGE_SIZE || 10, 10),

  DATABASE_HOST,
  DATABASE_PORT,
  DATABASE_NAME,
  DATABASE_USERNAME,
  DATABASE_PASSWORD,
};
